# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SurvivalMo.de
email: hi@survivalmo.de
description: >
  A TIL blog that's a part of the developermo.de project
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://survivalmo.de" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Pranay Prakash'
bio: >
  I will be a survivor of the University of Illinois at Urbana-Champaign CS Program. I will also make it out of the triangl alive.
author_image: "/assets/images/author.jpg"
twitter_username: pranaygp
github_username:  pranaypg

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
